name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
    - run: |
        npm install
        npm run build tsc --noEmit
        
